name: attendance_app
description: Location-based class attendance system (student/teacher/admin)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  http: ^1.2.1                 # API calls
  shared_preferences: ^2.2.3   # store JWT token + role locally
  geolocator: ^12.0.0          # GPS location for attendance
  provider: ^6.1.2             # simple state management
  intl: ^0.19.0                # date formatting
  url_launcher: ^6.3.0         # open CSV download links in browser

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
