version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: att_postgres
    environment:
      POSTGRES_DB: attdb
      POSTGRES_USER: kmabdulalimshahin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
