require('./_env_setup.cjs');const path=require('path');const ROOT=path.resolve(__dirname,'..');require.cache[require.resolve(path.join(ROOT,'src/config/db.js'))]={exports:{query:async()=>({rows:[]})}};const sessions=new Map();const students=new Map();const records=new Map();const attStub={findSessionById:async(id)=>sessions.get(id)||null,findStudentById:async(id)=>students.get(id)||null,findExistingAttendance:async(s,x)=>records.get(s+':'+x)||null,insertAttendanceRecord:async(a)=>{const id='r'+Date.now();const r={id,session_id:a.sessionId,student_id:a.studentId,status:'PRESENT',marked_at:new Date(),marked_device_id:a.deviceId,marked_face_similarity:a.similarity,marked_is_mock_location:a.isMockLocation};records.set(a.sessionId+':'+a.studentId,r);return r;},insertAuditLog:async()=>{}};require.cache[require.resolve(path.join(ROOT,'src/modules/attendance/attendance.repo.js'))]={exports:attStub};const bioStub={findStudentByDeviceId:async(d)=>{for(const s of students.values())if(s.device_id===d)return s;return null;},findStudentById:async(id)=>students.get(id)||null,bindFaceAndDevice:async({studentId,deviceId,ciphertext,iv,authTag})=>{const s=students.get(studentId);if(!s)return null;s.device_id=deviceId;s.is_device_locked=true;s.face_is_encrypted=true;s.face_embedding_encrypted=ciphertext;s.face_embedding_iv=iv;s.face_embedding_auth_tag=authTag;return s;}};require.cache[require.resolve(path.join(ROOT,'src/modules/biometrics/biometrics.repo.js'))]={exports:bioStub};const bio=require(path.join(ROOT,'src/modules/biometrics/biometrics.service'));const att=require(path.join(ROOT,'src/modules/attendance/attendance.service'));function vec(seed){const v=new Array(128);for(let i=0;i<128;i++)v[i]=Math.sin(seed+i)*0.5+0.5;return v;}function samePersonFace(seed){const v=vec(seed);v[5]+=0.0001;v[10]-=0.0001;return v;}function strangerFace(){const v=new Array(128);for(let i=0;i<128;i++)v[i]=(i%2===0?-0.9:0.9);return v;}let pass=0,fail=0;const log=(name,ok,extra='')=>{console.log((ok?'PASS':'FAIL')+' '+name+(extra?' :: '+extra:''));if(ok)pass++;else fail++;};const reset=()=>records.clear();async function main(){
const SID='st1';const DID='dev-abc';students.set(SID,{id:SID,full_name:'Nafis',email:'n@x',registration_no:'2023001',device_id:null,is_device_locked:false,face_is_encrypted:false,is_active:true});const SESS='sess1';sessions.set(SESS,{id:SESS,teacher_id:'t1',course_id:'c1',is_active:true,started_at:new Date(),expires_at:new Date(Date.now()+10*60*1000),center_lat:24.9172,center_lng:91.8319,radius_meters:50});
await bio.enrollFace({studentId:SID,deviceId:DID,embeddings:[vec(1),vec(2),vec(3)]});log('A:enroll',students.get(SID).is_device_locked===true);
reset();let r=await att.markAttendance({sessionId:SESS,studentId:SID,deviceId:DID,lat:24.91721,lng:91.83191,isMockLocation:false,faceEmbedding:samePersonFace(2)});log('B:happy',!!(r&&r.attendance&&r.attendance.id),r.attendance?'sim='+r.similarity.toFixed(4):'no-record');
reset();try{await att.markAttendance({sessionId:SESS,studentId:SID,deviceId:'dev-OTHER',lat:24.91721,lng:91.83191,isMockLocation:false,faceEmbedding:vec(2)});log('C:devMismatch',false,'no-throw');}catch(e){log('C:devMismatch',e.code==='DEVICE_MISMATCH',e.code);}
reset();try{await att.markAttendance({sessionId:SESS,studentId:SID,deviceId:DID,lat:24.900,lng:91.83191,isMockLocation:false,faceEmbedding:vec(2)});log('D:geoOut',false,'no-throw');}catch(e){log('D:geoOut',e.code==='LOCATION_OUT_OF_RANGE',e.code);}
reset();try{await att.markAttendance({sessionId:SESS,studentId:SID,deviceId:DID,lat:24.91721,lng:91.83191,isMockLocation:true,faceEmbedding:vec(2)});log('E:mock',false,'no-throw');}catch(e){log('E:mock',e.code==='MOCK_LOCATION_DETECTED',e.code);}
reset();try{await att.markAttendance({sessionId:SESS,studentId:SID,deviceId:DID,lat:24.91721,lng:91.83191,isMockLocation:false,faceEmbedding:strangerFace()});log('F:faceMismatch',false,'no-throw');}catch(e){log('F:faceMismatch',e.code==='FACE_MISMATCH',e.code);}
await att.markAttendance({sessionId:SESS,studentId:SID,deviceId:DID,lat:24.91721,lng:91.83191,isMockLocation:false,faceEmbedding:samePersonFace(2)});try{await att.markAttendance({sessionId:SESS,studentId:SID,deviceId:DID,lat:24.91721,lng:91.83191,isMockLocation:false,faceEmbedding:samePersonFace(3)});log('G:doubleMark',false,'no-throw');}catch(e){log('G:doubleMark',e.code==='ATTENDANCE_ALREADY_MARKED',e.code);}
} main().then(()=>{console.log('---');console.log('TOTAL pass='+pass+' fail='+fail);process.exit(fail?1:0);}).catch(e=>{console.error('THROWN:',e.code,e.message);process.exit(2);});
