name: mobile_app
description: "SUST Attendance Tracker"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Networking, WebSockets & Storage
  http: ^1.2.1
  flutter_secure_storage: ^9.0.0
  socket_io_client: ^3.0.2
  provider: ^6.1.2

  # Security & Dynamic QR
  crypto: ^3.0.3
  qr_flutter: ^4.1.0

  # Hardware ID & Location
  device_info_plus: ^10.1.0
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  mobile_scanner: ^5.1.1

  # Camera & Face ML Kit
  camera: ^0.11.0+1
  google_mlkit_face_detection: ^0.11.0
  tflite_flutter: ^0.12.1
  image: ^4.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/models/mobilefacenet.tflite